//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.DataLayer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Id { get; set; }
        public Nullable<int> QuestionTypeId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ThemeId { get; set; }
        public Nullable<int> TestId { get; set; }
        public string Text { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
